### ISSUE TITLE
Possible Bug? `per_resource = T` drops the `finished` variable in `get_mon_arrivals()`

### ISSUE THREAD

**Issue by las-matthew-bennett** [Enchufa2/simmer#295] opened 2023-03-09 16:49 UTC
Unless I'm missing something obvious, shouldn't the `per_resource` argument simply add a new column to the data frame given, rather than replace the `finished` column?

### Current  behaviour
```
get_mon_arrivals(my_envs, per_resource = FALSE)

                                  name start_time  end_time  activity_time   finished replication
1    dispatcher_abstraction4    63.0000 103.6759       40.67585     TRUE                1
2    dispatcher_abstraction0    11.0000 111.9138     100.91381     TRUE                1
```

```
get_mon_arrivals(my_envs, per_resource = TRUE)

                                  name start_time  end_time  activity_time    resource  replication
1    dispatcher_abstraction4    63.0000 103.6759       40.67585   dispatch                1
2    dispatcher_abstraction0    11.0000 111.9138     100.91381   dispatch                1
```

### Expected behaviour

```
get_mon_arrivals(my_envs, per_resource = TRUE)

                                  name start_time  end_time  activity_time    resource   finished replication
1    dispatcher_abstraction4    63.0000 103.6759       40.67585   dispatch       TRUE               1
2    dispatcher_abstraction0    11.0000 111.9138     100.91381   dispatch       TRUE               1
```

**Comment by Enchufa2** [comment] 2023-03-09 19:44
This is intended behavior. By default, the output tracks the lifetime of each arrival, and the `finished` column tells you whether the arrival completed its trajectory successfully or not. With `per_resource=TRUE`, the `finished` column has no meaning, because now you get the time spent per resource, so you get the `resource` column instead.

**Comment by las-matthew-bennett** [comment] 2023-03-10 10:43
Ah thank you. Sorry I've not been using the package long - but it seems extremely useful so thank you for that (and for the quick response!). Do I understand that I should see a `finished = FALSE ` if a patient regeges during a trajectory? Or does renaging still count as a completed trajectory?

**Comment by Enchufa2** [comment] 2023-03-10 10:54
Correct: reneging, leaving the trajectory, etc., are recorded as _not finished_.

Closing here then, thanks for the report!

**Closed as completed by Enchufa2** 2023-03-10 10:54 UTC
