### ISSUE TITLE
Output options are too limited

### ISSUE THREAD

**Issue by bknotwell** [Enchufa2/simmer#298] opened 2023-04-06 16:29 UTC
I've started using simmer to generate test data using the `log_` primitive.  The output from the run is then sanitized with something like the following:

```
sed ’/^{ Source/d; /^{ Monitor/d; /^simmer/d;s/^.*{/{/’ | jq -s .
```

as I'm removing the headers of the logs as well as the lines with the final monitoring information.  It would be useful to have the following:

- a method to disable the final monitoring output
- a method to disable the log header information

If this already exists, it's not clear why I can't find it.

**Comment by Enchufa2** [comment] 2023-04-06 17:14
Could you please give a small example of what you are trying to achieve?

As the name of the [manual page](https://r-simmer.org/reference/log_.html) for the `log_` function suggests, it is intended for debugging, not for collecting data about the simulation. You should be able to get all you need from the [monitoring](https://r-simmer.org/reference/get_mon.html) values.

**Comment by Enchufa2** [comment] 2023-04-14 14:23
Closing here for lack of info. Please feel free to reopen if you have an example of what you are trying to do and what the issue is.

**Closed as completed by Enchufa2** 2023-04-14 14:23 UTC
